name: daily_dish
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  animated_custom_dropdown: ^3.0.0
  expansion_tile_card: ^3.0.0
  fluttertoast: ^8.2.4
  lottie: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.7.0
  iconsax: ^0.0.8
  multi_bloc_builder: ^1.0.0
  provider: ^6.0.0
  phosphor_flutter: ^2.0.1
  gif: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cake.gif
    - assets/roasted-turkey.gif
    - assets/stew.gif
    - assets/stew-nb.png
    - assets/cake-nb.png
    - assets/roasted-turkey-nb.png
    - assets/french-fries.png
    - assets/pasta.png
    - assets/salt.png
    - assets/steak.png
    - assets/sugar.png
    - assets/vegetables.png
    - assets/pretzel.png
    - assets/donuts.png
